delete from "M_CODE";
commit;
delete from "M_CODE" where 1=1 AND "CODE_DIV" = 'ITEM_TYPE' AND "KEY" = '001';
insert into "M_CODE" ("CODE_DIV", "KEY", "VAL", "DELETE_FLG", "CREATE_TIME", "CREATE_USER_ID", "UPDATE_TIME", "UPDATE_USER_ID") values ('ITEM_TYPE','001','衣類','0', to_date('2019/08/13','YYYY/MM/DD'),'SYSTEM', to_date('2019/08/13','YYYY/MM/DD'),'SYSTEM');
delete from "M_CODE" where 1=1 AND "CODE_DIV" = 'ITEM_TYPE' AND "KEY" = '002';
insert into "M_CODE" ("CODE_DIV", "KEY", "VAL", "DELETE_FLG", "CREATE_TIME", "CREATE_USER_ID", "UPDATE_TIME", "UPDATE_USER_ID") values ('ITEM_TYPE','002','食べ物','0', to_date('2019/08/13','YYYY/MM/DD'),'SYSTEM', to_date('2019/08/13','YYYY/MM/DD'),'SYSTEM');
delete from "M_CODE" where 1=1 AND "CODE_DIV" = 'ITEM_TYPE' AND "KEY" = '003';
insert into "M_CODE" ("CODE_DIV", "KEY", "VAL", "DELETE_FLG", "CREATE_TIME", "CREATE_USER_ID", "UPDATE_TIME", "UPDATE_USER_ID") values ('ITEM_TYPE','003','日用品','0', to_date('2019/08/13','YYYY/MM/DD'),'SYSTEM', to_date('2019/08/13','YYYY/MM/DD'),'SYSTEM');
delete from "M_CODE" where 1=1 AND "CODE_DIV" = 'USER_SEX' AND "KEY" = '1';
insert into "M_CODE" ("CODE_DIV", "KEY", "VAL", "DELETE_FLG", "CREATE_TIME", "CREATE_USER_ID", "UPDATE_TIME", "UPDATE_USER_ID") values ('USER_SEX','1','男','0', to_date('2019/08/13','YYYY/MM/DD'),'SYSTEM', to_date('2019/08/13','YYYY/MM/DD'),'SYSTEM');
delete from "M_CODE" where 1=1 AND "CODE_DIV" = 'USER_SEX' AND "KEY" = '2';
insert into "M_CODE" ("CODE_DIV", "KEY", "VAL", "DELETE_FLG", "CREATE_TIME", "CREATE_USER_ID", "UPDATE_TIME", "UPDATE_USER_ID") values ('USER_SEX','2','女','0', to_date('2019/08/13','YYYY/MM/DD'),'SYSTEM', to_date('2019/08/13','YYYY/MM/DD'),'SYSTEM');
delete from "T_ITEM";
commit;
delete from "T_ITEM" where 1=1 AND "ITEM_ID" = 'ITEM001';
insert into "T_ITEM" ("ITEM_ID", "ITEM_NAME", "ITEM_PRICE", "ITEM_DETAIL", "ITEM_PIC", "ITEM_PRODUCT_DATE", "ITEM_TYPE", "DELETE_FLG", "CREATE_TIME", "CREATE_USER_ID", "UPDATE_TIME", "UPDATE_USER_ID") values ('ITEM001','BAG',200,'ブランド品質',NULL, to_date('2015/06/21','YYYY/MM/DD'),'003','0', to_date('2019/08/13','YYYY/MM/DD'),'SYSTEM', to_date('2019/08/13','YYYY/MM/DD'),'SYSTEM');
delete from "T_ITEM" where 1=1 AND "ITEM_ID" = 'ITEM002';
insert into "T_ITEM" ("ITEM_ID", "ITEM_NAME", "ITEM_PRICE", "ITEM_DETAIL", "ITEM_PIC", "ITEM_PRODUCT_DATE", "ITEM_TYPE", "DELETE_FLG", "CREATE_TIME", "CREATE_USER_ID", "UPDATE_TIME", "UPDATE_USER_ID") values ('ITEM002','Mac PC',3000,'非常いい',NULL, to_date('2017/08/13','YYYY/MM/DD'),'003','0', to_date('2019/08/13','YYYY/MM/DD'),'SYSTEM', to_date('2019/08/13','YYYY/MM/DD'),'SYSTEM');
delete from "T_ITEM" where 1=1 AND "ITEM_ID" = 'ITEM003';
insert into "T_ITEM" ("ITEM_ID", "ITEM_NAME", "ITEM_PRICE", "ITEM_DETAIL", "ITEM_PIC", "ITEM_PRODUCT_DATE", "ITEM_TYPE", "DELETE_FLG", "CREATE_TIME", "CREATE_USER_ID", "UPDATE_TIME", "UPDATE_USER_ID") values ('ITEM003','thinkpad x390',6000,'GOOD!!',NULL, to_date('2012/01/03','YYYY/MM/DD'),'003','0', to_date('2019/08/13','YYYY/MM/DD'),'SYSTEM', to_date('2019/08/13','YYYY/MM/DD'),'SYSTEM');
delete from "T_ORDER";
commit;
delete from "T_ORDER" where 1=1 AND "ORDERS_NO" = '20190813_00000000001';
insert into "T_ORDER" ("ORDERS_NO", "USER_ID", "CREATETIME", "NOTE", "DELETE_FLG", "CREATE_TIME", "CREATE_USER_ID", "UPDATE_TIME", "UPDATE_USER_ID") values ('20190813_00000000001','tanaka', to_date('2019/08/13 13:13:09','YYYY/MM/DD HH24:MI:SS'),NULL,'0', to_date('2019/08/13','YYYY/MM/DD'),'SYSTEM', to_date('2019/08/13','YYYY/MM/DD'),'SYSTEM');
delete from "T_ORDER_DETAIL";
commit;
delete from "T_ORDER_DETAIL" where 1=1 AND "ORDERS_NO" = '20190813_00000000001' AND "SUB_ID" = '1  ';
insert into "T_ORDER_DETAIL" ("ORDERS_NO", "SUB_ID", "ITEM_ID", "ITEM_NUM", "DELETE_FLG", "CREATE_TIME", "CREATE_USER_ID", "UPDATE_TIME", "UPDATE_USER_ID") values ('20190813_00000000001','1  ','ITEM001',1,'0', to_date('2019/08/13','YYYY/MM/DD'),'SYSTEM', to_date('2019/08/13','YYYY/MM/DD'),'SYSTEM');
delete from "T_ORDER_DETAIL" where 1=1 AND "ORDERS_NO" = '20190813_00000000001' AND "SUB_ID" = '2  ';
insert into "T_ORDER_DETAIL" ("ORDERS_NO", "SUB_ID", "ITEM_ID", "ITEM_NUM", "DELETE_FLG", "CREATE_TIME", "CREATE_USER_ID", "UPDATE_TIME", "UPDATE_USER_ID") values ('20190813_00000000001','2  ','ITEM002',3,'0', to_date('2019/08/13','YYYY/MM/DD'),'SYSTEM', to_date('2019/08/13','YYYY/MM/DD'),'SYSTEM');
delete from "T_USER";
commit;
delete from "T_USER" where 1=1 AND "ID" = 'tanaka';
insert into "T_USER" ("ID", "USERNAME", "BIRTHDAY", "SEX", "ADDRESS", "PASSWORD", "TEL", "MAIL", "DELETE_FLG", "CREATE_TIME", "CREATE_USER_ID", "UPDATE_TIME", "UPDATE_USER_ID") values ('tanaka','田中',NULL,'2',NULL,'123456','08014345691','1@gmail.com','0', to_date('2019/08/13','YYYY/MM/DD'),'SYSTEM', to_date('2019/08/13','YYYY/MM/DD'),'SYSTEM');
delete from "T_USER" where 1=1 AND "ID" = 'suzuki';
insert into "T_USER" ("ID", "USERNAME", "BIRTHDAY", "SEX", "ADDRESS", "PASSWORD", "TEL", "MAIL", "DELETE_FLG", "CREATE_TIME", "CREATE_USER_ID", "UPDATE_TIME", "UPDATE_USER_ID") values ('suzuki','鈴木', to_date('2001/08/13','YYYY/MM/DD'),'1','大連','123456','08082245608','2@gmail.com','0', to_date('2019/08/13','YYYY/MM/DD'),'SYSTEM', to_date('2019/08/13','YYYY/MM/DD'),'SYSTEM');
delete from "T_USER" where 1=1 AND "ID" = 'sakawa';
insert into "T_USER" ("ID", "USERNAME", "BIRTHDAY", "SEX", "ADDRESS", "PASSWORD", "TEL", "MAIL", "DELETE_FLG", "CREATE_TIME", "CREATE_USER_ID", "UPDATE_TIME", "UPDATE_USER_ID") values ('sakawa','佐川',NULL,'2','上海','123456',NULL,'3@gmail.com','0', to_date('2019/08/13','YYYY/MM/DD'),'SYSTEM', to_date('2019/08/13','YYYY/MM/DD'),'SYSTEM');
